### ISSUE TITLE
Add Option to Hide Event Times

### ISSUE THREAD

**Issue by artistro08** [artistro08/tailor-starter#10]
There should be an option to hide the event date and times. This feature is needed because the event may not have a time, nor a date.

**Comment by webfalter** [comment]
Workaround
Enter the date anyway, with an extra switch 
is_ferien:
        label: Keine Schule
        tab: Edit
        type: switch
        comment: Keine Schule
        span: right
        cssClass: mt-lg-4 mt-0

and then intercept with Twig

  {% if is_ferien == 1 %}
 {% else %}
 {% endif %}

**Comment by artistro08** [comment]
Native support is for this is added now in v3.1.1
