### ISSUE TITLE
Installation on staging server issues

### ISSUE THREAD

**Issue by chrisvidal** [artistro08/tailor-starter#100]
the seeding of my exported data does not works well. Sometimes the content is imported, sometimes not.

for instance, all the main and secondary menu were not linked to the pages after import.

after manually set the main menu items one by one, the links are not working, instead of generating the link `/contact` it gives `/default` for all page links.

any idea?

EDIT: to make the page links works, I had to save again all the pages...ok maybe a Tailor issue

**Comment by artistro08** [comment]
Yeah that's a long standing tailor issue that I've been having myself.

**Comment by chrisvidal** [comment]
and i have an orphan page link that does not resolve :( whatever I do, the link is not generated. weird

**Comment by chrisvidal** [comment]
cant find a fix for now

**Comment by chrisvidal** [comment]
on my side, the issue seems to appear when a link is created from inside a richtexteditor with pagefinder

**Comment by artistro08** [comment]
Hmmm in that case it may not be getting parsed correctly when it's getting imported. 

I would file a bug if you want to get them to help

**Comment by chrisvidal** [comment]
i did post a bug

**Comment by chrisvidal** [comment]
the team says to check this article and doc: 

https://docs.octobercms.com/3.x/markup/filter/link.html

**Comment by chrisvidal** [comment]
in partial `builder/columns/content`

the fix is to replace `{{ column.content|raw }}` with `{{ column.content|content }}`

**Comment by artistro08** [comment]
Will implement a fix with this soon.
