### ISSUE TITLE
Issue with Form Flash Success Message

### ISSUE THREAD

**Issue by chrisvidal** [artistro08/tailor-starter#108]
The Flash success message dispay after a form submission is loosing the line return formatting.
Is there a way to quick fix this by any chance?

**Comment by artistro08** [comment]
Could you share a screenshot?

**Comment by chrisvidal** [comment]
form details:

<img width="932" alt="image" src="https://github.com/artistro08/tailor-starter/assets/2263496/25502728-edd9-4cf7-a870-1b2519a5993b">


Flash success result message display 

<img width="817" alt="image" src="https://github.com/artistro08/tailor-starter/assets/2263496/673f6f31-198e-45f6-8908-462afdacf318">

**Comment by artistro08** [comment]
Ahh. In the flash partial, try adding `|nl2br` to the flash message 

`{{ message|nl2br }}`

**Comment by chrisvidal** [comment]
yes that works in the `tailor_modules/form` thanks
