### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by chrisvidal** [artistro08/tailor-starter#110]
I am modifying the post page as Ineed to add a simple breadcrumbs.
Is there a twig way to create a link back to a page entry? (so not `| page`) to your knowledge?

I got this to work `<a href="{{  'page' | page({'fullslug':'blog'}) }}">Blog</a> > {{  post.title }}`

**Comment by artistro08** [comment]
Actually yes but it uses the `|page` filter. You can reference the page by using the `{{ page.parent }}` variable.
