### ISSUE TITLE
Form Fields Dropdown

### ISSUE THREAD

**Issue by chrisvidal** [artistro08/tailor-starter#115]
The dropdown option looks like we can customize them:
<img width="968" alt="image" src="https://github.com/artistro08/tailor-starter/assets/2263496/24217d68-53b2-4c44-bca2-9cf5b2428c18">

but the rendering of the form shows something else as the value for the options:

```html
<select name="date" class="form-select" aria-label="Date" id="date">
      <option selected="" disabled="">Veuillez sélectionner une date</option>
      <option value="Mardi 21 Nov. 2023, 20h15-21h45">Mardi 21 Nov. 2023, 20h15-21h45</option>
      <option value="Jeudi 12 Oct. 2023, 20h-21h30">Jeudi 12 Oct. 2023, 20h-21h30</option>
</select>
```

**Comment by artistro08** [comment]
Fixed. thanks for the pull request!
