### ISSUE TITLE
Theme doesn't start

### ISSUE THREAD

**Issue by h55ud3h** [artistro08/tailor-starter#130]
Hello,
I try install this theme on my virtual machine with October 3.6.26
Install success. But something wrong
![2024-07-21_223134](https://github.com/user-attachments/assets/d6ae4bbc-d57d-47e2-9276-6a54d85f2013)
![2024-07-21_223155](https://github.com/user-attachments/assets/a7e009ba-e32a-48a2-9e4f-c4ab4881ab19)
![2024-07-21_223313](https://github.com/user-attachments/assets/17a3e246-5a2b-4358-8ab7-fea98bd9eff4)
![2024-07-21_223411](https://github.com/user-attachments/assets/35d6f5f3-3bd8-408f-97f0-c004e9b1929e)
![2024-07-21_223540](https://github.com/user-attachments/assets/8db4912a-33cd-4e38-9895-ee5e90a4dabd)

**Comment by artistro08** [comment]
That's expected. You need to set a homepage under the settings global in the backend then you will have a homepage.
