### ISSUE TITLE
What's Form Feature?

### ISSUE THREAD

**Issue by envas** [artistro08/tailor-starter#131]
In the dependencies you write 'Depends on [Artistro08.TailorStarterCompanion](https://octobercms.com/plugin/artistro08-tailorstartercompanion) ...  For Email Notifications with the [Forms Feature](https://octobercms.com/theme/broken-reference)'. However, the Forms Feature link is broken.

What does it mean the `Forms Feature`.

**Comment by artistro08** [comment]
Looks like I need to update the documentation. Forms is built into the theme's tailor functions. I'll make sure that's specified in the code

**Comment by envas** [comment]
OK, I found it, it's the `onFormSubmit()` in the page layout. Thank you.
