### ISSUE TITLE
Create Form Submission for Tailor

### ISSUE THREAD

**Issue by artistro08** [artistro08/tailor-starter#15]
Would be awesome if we could use Tailor to integrate Magic Forms into the theme with some Form builder logic

- [x] Create Tailor Blueprint with appropriate fields
- [x] Put Logic into Magic Forms
- [x] Profit

**Comment by artistro08** [comment]
This would need a version bump since it would not require Janvince's Small Contact Form Plugin

Also an extra note, The Magic Forms plugin was ported to the store: https://octobercms.com/plugin/blakejones-magicforms

**Comment by artistro08** [comment]
Tailor Logic is in place, just need to integrate it via the PHP code fields.

**Comment by artistro08** [comment]
This is gonna require a plugin extension for it to work. Will be added to the Tailor Starter companion plugin.

**Comment by artistro08** [comment]
Plan of Attack for Forms

- [ ] Create Validation via AJAX Data Attributes (Javascript)
- [ ] Create Mail Templates for notifications (Hook into Events)
- [ ] Add File Upload Support

**Comment by artistro08** [comment]
Originally, I was going to integrate Magic Forms into this theme, but since October CMS has all the features to implement a custom form directly into the theme, It makes sense to use the readily available tech to create a form using Tailor. This is exactly what I'll do.

**Comment by webfalter** [comment]
@artistro08 
Have you made any progress?
Best wishes

**Comment by artistro08** [comment]
Working on it as we speak. Just taking longer than expected.

**Comment by artistro08** [comment]
Added in v4.0.2
