### ISSUE TITLE
reCaptcha settings?

### ISSUE THREAD

**Issue by chrisvidal** [artistro08/tailor-starter#22]
After removing the martinforms plugin, thelink to pevious reCapatch plugin settings is not working anymore

<img width="285" alt="image" src="https://user-images.githubusercontent.com/2263496/215000675-63d1e65d-b872-4c04-9060-29f8d0cf6fd6.png">

**Comment by artistro08** [comment]
Could you go into some details there? The theme has it's own recaptcha settings.

**Comment by chrisvidal** [comment]
yes I found the settings.
the screenshot above is highlighting that the link to recapatcha settings is incorrect.

**Comment by artistro08** [comment]
Ahh okay. I'll fix it in the next build

**Comment by artistro08** [comment]
Fixed in the 5.0 Release.

Planned release date is today.
