### ISSUE TITLE
Add custom css class for all content block

### ISSUE THREAD

**Issue by chrisvidal** [artistro08/tailor-starter#23]
Would be great to be able to add a custom CSS class for each content and section blocks

**Comment by artistro08** [comment]
Currently the blocks are geared towards clients and I don't think that should be a thing that the client should see. I could however add tabs to each block and make those specific items hidden by default. 

Could you let me know your reasoning behind this? I want to add it, but I also don't want to confuse the people using theme.

**Comment by chrisvidal** [comment]
That's a good point, I understand where you are coming from, it makes sense.

I just want to be able to add CSS or javascript handles for some specific code in my theme.
For example if I want to add some parallax effect in one section in particular.

**Comment by artistro08** [comment]
Fixed in the 5.0 Release. I added Custom CSS Classes and IDs for each section under the Advanced tab.

Planned release date is today.
