### ISSUE TITLE
Bootstrap setup

### ISSUE THREAD

**Issue by chrisvidal** [artistro08/tailor-starter#24]
I noticed that, for instance, the buttons style definition, are not using the CSS variable but the hardcoded colors.

for example:

```
.btn-primary {
  --bs-btn-color: #fff;
  --bs-btn-bg: #0d6efd;
  --bs-btn-border-color: #0d6efd;
  --bs-btn-hover-color: #fff;
  --bs-btn-hover-bg: #0b5ed7;
  --bs-btn-hover-border-color: #0a58ca;
  --bs-btn-focus-shadow-rgb: 49, 132, 253;
  --bs-btn-active-color: #fff;
  --bs-btn-active-bg: #0a58ca;
  --bs-btn-active-border-color: #0a53be;
  --bs-btn-active-shadow: inset 0 3px 5px rgba(0, 0, 0, 0.125);
  --bs-btn-disabled-color: #fff;
  --bs-btn-disabled-bg: #0d6efd;
  --bs-btn-disabled-border-color: #0d6efd;
}
```

where it could be

```
.btn-primary {
  --bs-btn-color: #fff;
  --bs-btn-bg: var(--bs-primary);
  --bs-btn-border-color: var(--bs-primary);
  --bs-btn-hover-color: #fff;
  --bs-btn-hover-bg: #0b5ed7;
  --bs-btn-hover-border-color: #0a58ca;
  --bs-btn-focus-shadow-rgb: 49, 132, 253;
  --bs-btn-active-color: #fff;
  --bs-btn-active-bg: #0a58ca;
  --bs-btn-active-border-color: #0a53be;
  --bs-btn-active-shadow: inset 0 3px 5px rgba(0, 0, 0, 0.125);
  --bs-btn-disabled-color: #fff;
  --bs-btn-disabled-bg: var(--bs-primary);
  --bs-btn-disabled-border-color: var(--bs-primary);
}
```

**Comment by artistro08** [comment]
I'm sure I just need to update the version of bootstrap. I'll do this over the weekend if I have time.

**Comment by artistro08** [comment]
@chrisvidal, so I did update the version of bootstrap. but it still includes the hardcoded colors. 

This is how bootstrap does it, and I don't think it would be wise to change it if it's default. This would cause a bit of confusion when pulling in themes that require the core version of bootstrap. 

With that being said, I don't think I'll do this, but you can always add your own css to override those variables.

**Comment by chrisvidal** [comment]
then I guess it is a bug in Bootstrap :)
when changing the primary colour, it should change the color of the primary button with it.
