### ISSUE TITLE
Section vertical padding and Disable Top / Bottom Spacing

### ISSUE THREAD

**Issue by chrisvidal** [artistro08/tailor-starter#29]
Section vertical padding and Disable Top / Bottom Spacing is not working properly in general over the different pages and possibility.
For instance, the partial `events` and `products` does not handle the `disable` options and in general the `section` HTML tag does not have any vertical padding, so the options `disable` does not do anything.

I will try to submit a general submit for that matter.

**Comment by chrisvidal** [comment]
My idea is to add a global setting to choose the default vertical padding for a section.
Then user can disable top and / or bottom section by section if he wants to with the existing options

**Comment by artistro08** [comment]
@chrisvidal That was my initial plan. I'll work on adding that now.

**Comment by artistro08** [comment]
Fixed in the 5.0 Release.

Planned release date is today.
