### ISSUE TITLE
add default app.js 

### ISSUE THREAD

**Issue by chrisvidal** [artistro08/tailor-starter#51]
suggest to add an empty `js/app.js` and already integrated in all the resources component of the existing layouts.
right now, I have to override ALL the layouts just to add my custom `app.js`. I think it will be helppful for anyone else.

**Comment by artistro08** [comment]
I think so too. The caveat to this is that every project is different and it wouldn't make sense to include a file that isn't following their naming conventions. 

I think what we should do instead is include a partial specifically for assets so editing files can be easier.

**Comment by artistro08** [comment]
I actually did just that in v5.0.3. I moved all the assets to a new partial called `assets.htm` so you don't have to touch the layout files. It makes for adding assets easier in my opinion.
