### ISSUE TITLE
after latest update with v5.1.0

### ISSUE THREAD

**Issue by chrisvidal** [artistro08/tailor-starter#55]
only the homepage is working, all my previous existing page are an error 404 after the update.
Not sure what is happening, I am looking into it.
EDIT: I had to re-save all the page content to fix this

**Comment by artistro08** [comment]
Thanks for letting me know. I apologize for the breaking changes. 

I've included it in the release notes in the latest release. 

Just a heads up, I plan to release a v6.0.0 version here this week that includes the `pagefinder` widget.  This will break a lot of things, but after this version, I plan to add backwards compatibility for upcoming features after v6.0.0. 

You can keep an eye on the develop branch to see the breaking changes.
