### ISSUE TITLE
Namespace Change may Break Things

### ISSUE THREAD

**Issue by artistro08** [artistro08/tailor-starter#63]
So in light of submitting the plugin to the October CMS Marketplace for easier integration of projects, I had to change the namespace for the plugin and the theme. 

This may break things, but so far, I haven't had an issue. If you do have one, let me know and I'll do my best to fix things.

**Comment by chrisvidal** [comment]
I initially added the theme with the command to add theme pointing directly to the github repo, I think this should be ok

**Comment by artistro08** [comment]
Closing as it doesn't seem like it's causing too much of a problem
