### ISSUE TITLE
Issue with PageFinder

### ISSUE THREAD

**Issue by chrisvidal** [artistro08/tailor-starter#68]
Can't select any CMS page

<img width="813" alt="image" src="https://user-images.githubusercontent.com/2263496/218940902-653509b1-777a-4ebe-8154-9ce016a60e05.png">

**Comment by artistro08** [comment]
I am not 100% sure why this would happen. I did however try and test it on my computer and the CMS pages did come up correctly. Have you altered the blueprints in any way?

**Comment by chrisvidal** [comment]
so it works on the fresh install but the issue is happening on an upgraded and overridden version.
yes I have some blueprint on my end just to add a block to the builder. The rest is not altered especially the menu.
However, the page `page` and the layout `page` are altered, would that be coming from that?

**Comment by artistro08** [comment]
What's the URL parameter for that page? If I had to take a guess, since I had to default everything to "`:slug`" and "`:fullslug`" It would cause problems.

**Comment by chrisvidal** [comment]
for the page URL is `/:fullslug*`

**Comment by artistro08** [comment]
can you drop the component configuration here?

**Comment by chrisvidal** [comment]
> can you drop the component configuration here?
what do you mean?

**Comment by artistro08** [comment]
Can you screenshot or copy the text for your `[section]` component so I can see what it looks like? This should be in the `page.htm` file

**Comment by chrisvidal** [comment]
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/2263496/219689165-692e5eb6-a8e8-4147-bce3-a423d58f0f6d.png">

**Comment by artistro08** [comment]
Can you show me your child theme's content for `page.htm` if you have one?

**Comment by chrisvidal** [comment]
I dont have any overridden `pages` or `layout` in the child theme

**Comment by artistro08** [comment]
what version of OCS do you have?

**Comment by chrisvidal** [comment]
3.2.14

**Comment by artistro08** [comment]
I would see if it's a bug with October CMS. Check and email the team at hello@octobercms.com
