### ISSUE TITLE
Global Settings

### ISSUE THREAD

**Issue by webfalter** [artistro08/tailor-starter#69]
If I end in the global settings, like in the picture (collapse)

![Bildschirmfoto 2023-02-15 um 15 56 05](https://user-images.githubusercontent.com/481551/219064939-26e301c4-2b7f-42cc-94cb-3e42382abe74.png)

The whole thing comes up when you call up the setting again

![Bildschirmfoto 2023-02-15 um 15 56 24](https://user-images.githubusercontent.com/481551/219065071-7f866d83-29ee-49b0-845b-beaf737f0ac5.png)

**Comment by artistro08** [comment]
I believe there is no yaml setting to remember those are closed. To remedy this, I just added a `itemsExpanded` option and set it to false. This would at least solve part of the problem. 

added in v6.2.5
