### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by chrisvidal** [artistro08/tailor-starter#72]
this is my search settings

<img width="600" alt="image" src="https://user-images.githubusercontent.com/2263496/219236760-c91468f5-f4c7-4b26-b4fc-ab132ed7d748.png">

I have a About Us page with some dummy content as such

<img width="1260" alt="image" src="https://user-images.githubusercontent.com/2263496/219236994-ef546d1f-b44e-4e95-8d04-936ef687e056.png">

and I have no results for the search term `donor`

<img width="1133" alt="image" src="https://user-images.githubusercontent.com/2263496/219237199-164fecd2-c1e6-44fc-a753-05fcbdf3db27.png">

What am I missing here?

**Comment by artistro08** [comment]
Right now, it only searches the title content per the documentation: https://artistro08.gitbook.io/tailor-starter-documentation/search#how-search-works

I haven't tested using the builder repeater fields for searching, but you can try it and see how it works

**Comment by chrisvidal** [comment]
got it, thanks. it works for the page title only on my side

**Comment by artistro08** [comment]
That's the goal. Not sure how to get repeater data working, so I opened a [forum post](https://talk.octobercms.com/t/searchwhere-in-repeater-fields/1037) to see if we can. In the meantime, I'll close this.

**Comment by artistro08** [comment]
I just expanded the search to query the richeditor content from the blocks in v6.3.4

**Comment by artistro08** [comment]
one last update, The search query for this is set to content blocks with richeditor content, but the code is cleaner now.
