### ISSUE TITLE
top-level / parent page choice issue

### ISSUE THREAD

**Issue by chrisvidal** [artistro08/tailor-starter#74]
Not sure why there is 2 `home` listed here.

<img width="353" alt="image" src="https://user-images.githubusercontent.com/2263496/219573902-5a8c23e9-bc86-4eea-9f7a-61bc57319ea4.png">

**Comment by artistro08** [comment]
Unfortunately, this isn't something that I can fix. Looks like an October CMS Bug. I would talk to the developers and see what's up

**Comment by chrisvidal** [comment]
it looks like it keeps showing the deleted page

**Comment by artistro08** [comment]
That would make sense. I would check the database and see where it's being referenced.
