### ISSUE TITLE
"Use a CMS route prefix" option doesn't work properly with main menu links

### ISSUE THREAD

**Issue by haralake** [artistro08/tailor-starter#86]
If i enable "Use a CMS route prefix" option on Manage Sites settings and use for example prefix /fr, the links on main menu doesn't work because do not automatically add the prefix.

**Comment by artistro08** [comment]
Could you go into a bit more detail?

I was not able to reproduce the issue. I did run into some stuff while trying to get things in place. With that being said, I got a few questions:

Is the site enabled on the front-end?
Did you select page links for all the pages in the main menu?
Are the page links showing the URL with the prefix?

If the answer to those questions are yes, I would file a bug with the October CMS Team. [Head here](https://octobercms.com/support) to get in contact with them

**Comment by haralake** [comment]
The problem is in 2 lines:
First problem with logo link this code:
`{{ '/'|app ~ '/' ~ locale }}`
always gives http://mysite.com/en , even if locale prefix is not activated in language settings.

Second problem with this code:
`{{ settings.homepage.fullslug in item.page|link ? '/' : item.page|link }}`
even if prefix is enabled you still get http://mysite.com

**Comment by artistro08** [comment]
That helps alot. I can figure out a fix for these two in the meantime.

**Comment by artistro08** [comment]
Try and use v6.3.18 and see if that helps.

**Comment by haralake** [comment]
I proceeded with the changes but unfortunately the result is exactly the same.

Another problem I noticed is that if you change the language the main menu doesn't work at all. Searching I found that the tailor pagefinder field does not adopt the link when we change the language on a multilingual site.
In the admin in the primary language you see this:
![Screenshot_2](https://user-images.githubusercontent.com/18325407/223992551-d56413f6-c814-4081-9206-4ba7158bdc82.png)
and in the secondary language this:
![Screenshot_3](https://user-images.githubusercontent.com/18325407/223992928-6af2eba2-d00f-4052-9fc5-55f4606b3659.png)

**Comment by artistro08** [comment]
This may be a bug with October CMS then. I'll keep this open just in case.

**Comment by artistro08** [comment]
So there was some issues with my code, and some bugs with the platform. 

In order to fix mine, I had to set the theme to another theme, and update the multisite prefix to be empty. As far as the urls go, they should follow the multisite settings.

Just make sure you clear out the prefix if you want to turn it off. Just a heads up. 

Thanks again for reporting!
