### ISSUE TITLE
Unknown "icon" filter.

### ISSUE THREAD

**Issue by Hessel91** [artistro08/tailor-starter#90]
Hi, 

I used the icon tab to add svg icons to the social menu in the backend, but can I use the same svg's in my front-end code?

I added below code to the backed /tailor/entries/content_icon/ , saved and published it, named "test"

`<svg width="8" height="90" viewBox="0 0 8 90" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M0 0H8L4 90L0 0Z" fill="#343035"/>
</svg>`

and in my code `{{ 'test'|icon }}`

however below error occus, 

"Unknown "icon" filter."

Is there a config file were I can enable this filter?

**Comment by artistro08** [comment]
There is no icon filter with the icon sets. 


You should use 


`{{ test.svg_code|raw }}`

To display the icon.
