### ISSUE TITLE
how to disable stipe pay?

### ISSUE THREAD

**Issue by yellotra** [artistro08/tailor-starter#92]
Hi! how to disable the mandatory stripe (if only email notifications about the order are needed)

**Comment by artistro08** [comment]
There is no way to disable stripe. 

The shop is heavily ingrained with straight and uses web hooks in order to send emails. So if you plan on disabling this feature, you'll have to create your own workflow using October CMS events

**Comment by artistro08** [comment]
Closing as completed.
