### ISSUE TITLE
Question: how to handle reusable section

### ISSUE THREAD

**Issue by chrisvidal** [artistro08/tailor-starter#99]
I have a section offering some CTA that is present at the bottom of every page.
client can change image, text and buttons.

Did you face this scenario, and if yes, how did you find a way to reuse the section through different pages?

**Comment by artistro08** [comment]
If I know it's gonna be a global thing, I use the settings global and add the configuration there. 

I also configure each page to turn it off if I don't need it.

**Comment by chrisvidal** [comment]
I see. thanks for sharing. 
in my scenario, I will have multiple potential CTA templates (3 most likely).
Could do a repeater in the Global Settings to set image and text and link.
But how to link them into a page, and giv the client the choice of the CTA?

**Comment by artistro08** [comment]
In that case, I would add a attribute to the page entry type and use that to hook into the global repeater that you want to add
